Switch to ccc
konnectors/cozy-konnector-sosh pull request #557
Opened 2023-02-09 16:40 UTC by KillianCourvoisier

2023-02-09 18:02 UTC, KillianCourvoisier commented
Il y a des petites corrections a apporter au login/autologin, je suppose que comme Orange, le reste des actions ne nécessitera pas de changements, mais on ne dispose plus d'aucun comptes pour dev, il faut en trouver un nouveau.
Je laisse la PR en WIP en attendant.

2023-02-17 10:05 UTC, doubleface requested changes

2023-02-17 10:05 UTC, doubleface commented on .travis.yml
>  cache:
You forgot to add cozy_ccc space in yarn cozyPublish commands

2023-02-17 10:06 UTC, doubleface commented
Once the correct space is put in travis config file, it will be ok for me

2023-02-17 12:05 UTC, doubleface approved these changes

2023-02-17 12:11 UTC, merged